### PR TITLE
Updated Life Beyond the Borders Episode - 02

### PR DESCRIPTION
**Pull request by Abdus-Samee**
I was unaware of the fact that the pull request would update automatically on changing the forked repository. So, I've deleted the previous one. However, I've changed the folder name styles and updated the activitiesByCategory.yml file. I've also updated the android workshop folder and its links and overviews.

### CODE REVIEW

**Comment by Abdus-Samee** [comment]
@imranhasanhira bhai I've changed the folder names and contents. Please look if it's correct.

**Review by imranhasanhira — APPROVED** [review]

**Review by imranhasanhira — APPROVED** [review]

**Comment by Abdus-Samee** [comment]
@imranhasanhira bhai, I've corrected the folder names. Hope there will no longer be any conflicts.

**Comment by imranhasanhira** [comment]
> @imranhasanhira bhai, I've corrected the folder names. Hope there will no longer be any conflicts.

looks like there are still few files left. Can you check again?

**Comment by Abdus-Samee** [comment]
@imranhasanhira bhai.. I've corrected it once again. The folder names seem to  change every time a commit is pushed. I hope this time it works.

**Pull request merged**
